name: smart_attendance_system
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.0+4
  fluttertoast: ^8.2.2
  get: ^4.6.5
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.11.1
  firebase_storage: ^11.5.6
  firebase_core: ^2.24.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  date_format: ^2.0.7
  intl: ^0.18.0
  camera: ^0.10.5+6
  image_picker: ^1.0.5
  firebase_cached_image: ^0.5.2
  firebase_database: ^10.4.5
  amplify_auth_cognito: ^1.7.2
  amplify_storage_s3: ^1.7.0
  amplify_flutter: ^1.7.0
  amplify_authenticator: ^1.5.5
  responsive_sizer: ^3.3.1
  http: ^1.2.1
  url_launcher: ^6.2.6
  map_launcher: ^3.3.0
  auto_size_text: ^3.0.0
  easy_localization: ^3.0.7
  syncfusion_flutter_charts: ^25.2.5






dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  assets:
    - images/
