// import React, {useEffect} from 'react';
// import './App.css';
// import ipec from './ipec_logo.png';
// import { useState } from 'react';
// import { useNavigate } from 'react-router-dom';
// import {Amplify} from 'aws-amplify';
// import {
//   BrowserRouter as Router,
//   Link,
//   Routes,
//   Route,
// } from 'react-router-dom';
// import { Authenticator, withAuthenticator } from '@aws-amplify/ui-react';
// import awsExports from './aws-exports';
// import HomePage from './homepage';
// // Imports the Authenticator and withAuthenticator components from '@aws-amplify/ui-react'.
// // Authenticator is a React component that provides a ready-to-use sign-in and sign-up UI.
// // withAuthenticator is a higher-order component that wraps your app component to enforce authentication.


// // Imports the default styles for the Amplify UI components. This line ensures that the authenticator looks nice out of the box.

// // Imports the awsExports configuration file generated by the Amplify CLI. This file contains the AWS service configurations (like Cognito, AppSync, etc.) specific to your project.

// // Imports the Quiz component from Quiz.js for use in this file.
// //import Quiz from './Quiz';


// // Configures the Amplify library with the settings from aws-exports.js, which includes all the AWS service configurations for this project.
// Amplify.configure(awsExports);

// const components = {
//   Header() {
//     const { tokens } = useTheme();

//     return (
//       <View textAlign="center" padding={tokens.space.large}>
//         <Image
//           alt="IPEC logo"
//           src={ipec}
//           height = {100}
//           width={100}
//         />
//       </View>
//     );
//   },

//   Footer() {
//     const { tokens } = useTheme();

//     return (
//       <View textAlign="center" padding={tokens.space.large}>
//         <Text color={tokens.colors.neutral[80]}>
//           &copy; All Rights Reserved
//         </Text>
//       </View>
//     );
//   },

//   SignIn: {
//     Header() {
//       const { tokens } = useTheme();

//       return (
//         <Heading
//           padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
//           level={3}
//         >
//           Sign in to your account
//         </Heading>
//       );
//     },
//     Footer() {
//       const { toForgotPassword } = useAuthenticator();

//       return (
//         <View textAlign="center">
//           <Button
//             fontWeight="normal"
//             onClick={toForgotPassword}
//             size="small"
//             variation="link"
//           >
//             Reset Password
//           </Button>
//         </View>
//       );
//     },
//   },

//   SignUp: {
//     Header() {
//       const { tokens } = useTheme();

//       return (
//         <Heading
//           padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
//           level={3}
//         >
//           Create a new account
//         </Heading>
//       );
//     },
//     Footer() {
//       const { toSignIn } = useAuthenticator();

//       return (
//         <View textAlign="center">
//           <Button
//             fontWeight="normal"
//             onClick={toSignIn}
//             size="small"
//             variation="link"
//           >
//             Back to Sign In
//           </Button>
//         </View>
//       );
//     },
//   },
//   ConfirmSignUp: {
//     Header() {
//       const { tokens } = useTheme();
//       return (
//         <Heading
//           padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
//           level={3}
//         >
//           Enter Information:
//         </Heading>
//       );
//     },
//     Footer() {
//       return <Text>Footer Information</Text>;
//     },
//   },
//   SetupTotp: {
//     Header() {
//       const { tokens } = useTheme();
//       return (
//         <Heading
//           padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
//           level={3}
//         >
//           Enter Information:
//         </Heading>
//       );
//     },
//     Footer() {
//       return <Text>Footer Information</Text>;
//     },
//   },
//   ConfirmSignIn: {
//     Header() {
//       const { tokens } = useTheme();
//       return (
//         <Heading
//           padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
//           level={3}
//         >
//           Enter Information:
//         </Heading>
//       );
//     },
//     Footer() {
//       return <Text>Footer Information</Text>;
//     },
//   },
//   ForgotPassword: {
//     Header() {
//       const { tokens } = useTheme();
//       return (
//         <Heading
//           padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
//           level={3}
//         >
//           Enter Information:
//         </Heading>
//       );
//     },
//     Footer() {
//       return <Text>Footer Information</Text>;
//     },
//   },
//   ConfirmResetPassword: {
//     Header() {
//       const { tokens } = useTheme();
//       return (
//         <Heading
//           padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
//           level={3}
//         >
//           Enter Information:
//         </Heading>
//       );
//     },
//     Footer() {
//       return <Text>Footer Information</Text>;
//     },
//   },
// };

// const formFields = {
//   signIn: {
//     username: {
//       placeholder: 'Enter your email',
//       order: 1,      
//     },
//     'custom:Category':{
//       label : 'Role',
//       placeholder : 'Student or Faculty?',
//       order: 5,
//     },
//   },
//   signUp: {
//     name: {
//       label: 'Name',
//       placeholder: 'Enter your name',
//       order: 1,
//     },
//     email: {
//       label: 'Email',
//       placeholder: 'Enter your email',
//       order: 2,
//     },
//     password: {
//       label: 'Password:',
//       placeholder: 'Enter your Password:',
//       isRequired: false,
//       order: 3,
//     },
//     confirm_password: {
//       label: 'Confirm Password:',
//       order: 4,
//     },
//     'custom:category':{
//       label : 'Role',
//       placeholder : 'Student or Faculty?',
//       order: 5,
//     },
//     'custom:uni_rollnumber':{
//       label : 'University Roll Number',
//       placeholder : 'Enter university roll number',
//       order: 6,
//     }
//   },
//   forceNewPassword: {
//     password: {
//       placeholder: 'Enter your Password:',
//     },
//   },
//   forgotPassword: {
//     username: {
//       placeholder: 'Enter your email:',
//     },
//   },
//   confirmResetPassword: {
//     confirmation_code: {
//       placeholder: 'Enter your Confirmation Code:',
//       label: 'New Label',
//       isRequired: false,
//     },
//     confirm_password: {
//       placeholder: 'Enter your Password Please:',
//     },
//   },
//   setupTotp: {
//     QR: {
//       totpIssuer: 'test issuer',
//       totpUsername: 'amplify_qr_test_user',
//     },
//     confirmation_code: {
//       label: 'New Label',
//       placeholder: 'Enter your Confirmation Code:',
//       isRequired: false,
//     },
//   },
//   confirmSignIn: {
//     confirmation_code: {
//       label: 'New Label',
//       placeholder: 'Enter your Confirmation Code:',
//       isRequired: false,
//     },
//   },
// };

// export default function App() {
//   const navigate = useNavigate();
//   const [authState, setAuthState] = useState();

//   useEffect(() => {
//     if (authState === 'signedIn') {
//       navigate('/');
//     }
//   }, [authState, navigate]);

//   return (
//     <Router>
//       <Authenticator formFields={formFields} components={components} onStateChange={setAuthState}>
//         {({ signOut }) => (
//           <>
//             <button onClick={signOut}>Sign out</button>
//             <Link to="/">
//               <button>Go to Homepage</button>
//             </Link>
//           </>
//         )}
//       </Authenticator>
//     </Router>
//   );
// }

// // export default function App() {
//   // return (
//     // <Authenticator formFields={formFields} components={components}>
//       {/* {{({ signOut }) => <button onClick={signOut}>Sign out</button>}} */}
//     {/* </Authenticator>  */}
//   // );
// // }
// // 

// // export default function App() {
//   // return (
//     // <Router>
//       {/* <Authenticator formFields={formFields} components={components}> */}
//         {/* {({ signOut }) => ( */}
//           // <>
//               {/* <button onClick={signOut}>Sign out</button> */}
//             {/* <Link to="/"> */}
//               {/* <button>Go to Homepage</button> */}
//             {/* </Link> */}
//           {/* </> */}
//         // )}
//       {/* </Authenticator> */}
//       {/* </Router> */}
//   // );
// // }